spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/offer
    username: roaduser
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    user-url: http://localhost:8222/api/v1/users
server:
  port: 8050
